version: "3.9"

services:
    api:
        container_name: "youtube-data-fetcher-service"
        build: .
        ports:
            - 8000:8000
        volumes:
            - .:/usr/src/app
        environment:
            API_KEYS: 
            PORT: 8000
            FETCH_FREQUENCY: '* * * * *'
            DB_NAME: 
            MONGO_URI: 
            RUN_FETCH_CRON: true
            DATA_LIMIT: 10
            CRON_DATA_LIMIT: 50
